### ISSUE TITLE
为什么我的二维码长得很奇怪，根本扫不了

### ISSUE THREAD

**Issue by 1176358062** [wangrongding/wechat-bot#1]
如题

**Comment by wangrongding** [comment]
是不是终端尺寸不够？或者也可以试试把这个配置去掉试试

![image](https://user-images.githubusercontent.com/42437658/206122543-5cf3daa7-9117-4c90-99e8-3c556fb0b5e7.png)

**Comment by 5wszxt** [comment]
长得很奇怪可以将二维码复制下来，打开notepad++粘贴就显示正常了，必备软件

**Comment by RookieOHY** [comment]
设置一下qrcode的尺寸试一试
