### ISSUE TITLE
有没有办法做到连续语境呢

### ISSUE THREAD

**Issue by king19990102** [wangrongding/wechat-bot#10]

**Comment by wangrongding** [comment]
可以的,这么写
```ts
const api = new ChatGPTAPI({
  sessionToken: process.env.SESSION_TOKEN
})

const conversation = api.getConversation()

// send a message and wait for the response
const response0 = await conversation.sendMessage('What is OpenAI?')

// send a follow-up prompt to the previous message and wait for the response
const response1 = await conversation.sendMessage('Can you expand on that?')

// send another follow-up to the same conversation
const response2 = await conversation.sendMessage('Oh cool; thank you')
```

**Comment by king19990102** [comment]
这是官方的例子，但是实际用的时候一般只发一次，没有起到作用

**Comment by king19990102** [comment]
哦，我知道，因为每次都会new新的会话所以不连续

**Comment by king19990102** [comment]
哦，我知道，因为每次都会new新的会话所有不连续

**Comment by wangrongding** [comment]
对的，把那个单独放最外面

**Comment by Alex-Shen1121** [comment]
<img width="827" alt="image" src="https://user-images.githubusercontent.com/73343630/206559944-3e8f2812-3991-4478-bf4b-82895f402b77.png">
这个api是被移除了吗

**Comment by ottocsb** [comment]
@Alex-Shen1121 更新依赖，默认的版本没有这个api

**Comment by liuliuzx** [comment]
> @Alex-Shen1121 更新依赖，默认的版本没有这个api

@ottocsb 请问更新哪个依赖啊？

**Comment by ottocsb** [comment]
@liuliuzx chatgpt

**Comment by wangrongding** [comment]
哦哦， 最新的提交已经更新依赖了~上一个版本缺少部分 api

**Comment by yn-ayw** [comment]
> 对的，把那个单放最外面

放最外面啥意思阿？放在哪里？

**Comment by wangrongding** [comment]
> 放最外面啥意思阿？放在哪里？

哦哦，就是把 api 的声明放到函数外面。
已经更新代码了，重新 pull 下

**Comment by 183673639** [comment]
现在的上下文语意好像还是没有连续起来

**Comment by hh0318** [comment]
> 
是因为现在问答依赖不是chatGpt 变成openAi 了

**Comment by hh0318** [comment]
> 现在的上下文语意好像还是没有连续起来

是因为现在问答依赖不是chatGpt 变成openAi 了

**Comment by hushicai** [comment]
接入最新吧chatgpt，加上conversation支持就好了。

https://github.com/hushicai/wechat-bot/commit/dee4761f27699f70cd33ac4ea085bacec1af83dd

<img width="844" alt="image" src="https://user-images.githubusercontent.com/1249423/217478039-d7d2acef-c33e-4769-84b3-b5286e779cb9.png">
