### ISSUE TITLE
我启动不了应用

### ISSUE THREAD

**Issue by DavidWanBYS** [wangrongding/wechat-bot#105]
14:43:46 ERR PuppetWeChatBridge start() exception: Error: An `executablePath` or `channel` must be specified for `puppeteer-core`
14:43:46 ERR PuppetWeChat initBridge() exception: An `executablePath` or `channel` must be specified for `puppeteer-core`
14:43:46 ERR PuppetWeChat initBridge() this.bridge.stop() rejection: Error: no page
GError: An `executablePath` or `channel` must be specified for `puppeteer-core`
    at assert (C:\Users\admin\Documents\example\wechat-bot\node_modules\puppeteer-core\lib\cjs\puppeteer\util\assert.js:28:15)
    at ChromeLauncher.launch (C:\Users\admin\Documents\example\wechat-bot\node_modules\puppeteer-core\lib\cjs\puppeteer\node\ChromeLauncher.js:92:36)
    at PuppeteerNode.launch (C:\Users\admin\Documents\example\wechat-bot\node_modules\puppeteer-core\lib\cjs\puppeteer\node\PuppeteerNode.js:154:105)

**Comment by michaelrrrrrr** [comment]
我也出现了同样的问题……

**Comment by deardeer7** [comment]
解决了，翻翻issue，我是windows10，下载了作者临时解决方案中的Chrome，然后修改了ChromeLaucher.js为下载的chrome.exe的位置，就好了。

**Comment by wangrongding** [comment]
参考 #54

**Comment by klbnkg** [comment]
mac报错。

**Comment by DavidWanBYS** [comment]
> 解决了，翻翻issue，我是windows10，下载了作者临时解决方案中的Chrome，然后修改了ChromeLaucher.js为下载的chrome.exe的位置，就好了。

ok, thanks

**Comment by OnePieceJoker** [comment]
@DavidWanBYS 打扰下， 如果问题解决了，可以close下issue

**Comment by DavidWanBYS** [comment]
okay

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ZhiHong ***@***.***>
发送时间: 2023年2月20日 11:27
收件人: ***@***.***>
抄送: wandanhui ***@***.***>; ***@***.***>
主题: Re: [wangrongding/wechat-bot] 我启动不了应用 (Issue #105)


@DavidWanBYS<https://github.com/DavidWanBYS> 打扰下， 如果问题解决了，可以close下issue

―
