### ISSUE TITLE
请问我修改了删除了判定回复的人之后，ai就和自己聊起来了怎么办，代码该怎么修改

### ISSUE THREAD

**Issue by 2953225996** [wangrongding/wechat-bot#12]
![QQ截图20221208235209](https://user-images.githubusercontent.com/99384711/206494985-822df71e-0152-4e0a-a901-68a23fb86691.png)
![QQ截图20221208235427](https://user-images.githubusercontent.com/99384711/206494992-37b253b6-1d6c-455f-b581-a67b38c385d6.png)

**Comment by wangrongding** [comment]
可以自行看看 wechaty 文档哈，都有说明的
