### ISSUE TITLE
apiKey无效是什么原因，刚创建的

### ISSUE THREAD

**Issue by lickylu** [wangrongding/wechat-bot#125]
![QQ图片20230220100028](https://user-images.githubusercontent.com/101613629/219995712-3830032f-5c3b-47ea-af19-0ab3f11f81db.png)

**Comment by OnePieceJoker** [comment]
https://github.com/wangrongding/wechat-bot/issues/54#issuecomment-1436219981

**Comment by lickylu** [comment]
> [#54（评论）](https://github.com/wangrongding/wechat-bot/issues/54#issuecomment-1436219981)
直接把apikey设置到文件里运行后依旧报同样错误

**Comment by OnePieceJoker** [comment]
我重新看了下你的报错日志，发现你这边是引用了src/chatgpt/index.js？

**Comment by lickylu** [comment]
好的已更改，谢谢

**Comment by OnePieceJoker** [comment]
如果问题已解决，可以close下issue

**Comment by Pnawei** [comment]
![image](https://github.com/wangrongding/wechat-bot/assets/78192913/918789f4-9b20-4bfc-b254-bd610789c4cf)
