### ISSUE TITLE
run npm dev moudles报错

### ISSUE THREAD

**Issue by ToolRobot-1024** [wangrongding/wechat-bot#129]
Error: An `executablePath` or `channel` must be specified for `puppeteer-core`
![QQ截图20230224173407](https://user-images.githubusercontent.com/92771602/221144563-cced7982-f9d9-4c44-b7ce-53fcc95afbdf.png)

**Comment by alannewlife** [comment]
刚才也是报出了这个错误。
请问你解决了么？

**Comment by ToolRobot-1024** [comment]
用wechaty-puppet-wechat4u ，这个是不需要安装puppeteer的，纯api请求安装依赖，保证wechaty-puppet-wechat4u版本为 1.13.12npm i wechaty-puppet-wechat4u --save修改 src/wechaty/index.js文件中的内容...// 初始化机器人export const bot = WechatyBuilder.build({  name: 'WechatEveryDay',  puppet: 'wechaty-puppet-wechat4u',})...然后正常运行即可发自我的 iPhone在 2023年3月1日，15:52，alannewlife ***@***.***> 写道：﻿
刚才也是报出了这个错误。
请问你解决了么？

**Comment by alannewlife** [comment]
可以了。
但是api今天不通了。
