### ISSUE TITLE
正确的token替换到.env后运行报错

### ISSUE THREAD

**Issue by Anyyy111** [wangrongding/wechat-bot#13]
这是我的token，昨天早上的测试中bot都是可以正常开启的，但是我昨晚到现再次测试时好像token出了问题

求助如何解决！！

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/87168243/206590438-d0ed8103-7d35-41e8-81ad-f5f51afeb86d.png">

<img width="853" alt="image" src="https://user-images.githubusercontent.com/87168243/206590163-9a7c6129-8f1a-4631-89ba-016f86d61c6c.png">

<img width="856" alt="image" src="https://user-images.githubusercontent.com/87168243/206590391-ada3d3e0-f5a8-45f7-848b-0e44c8976489.png">

**Comment by wangrongding** [comment]
过期了~

**Comment by Anyyy111** [comment]
> 过期了~

没有吧，我尝试了好几个都是这样。刷新refresh也是

**Comment by wangrongding** [comment]
是的，我也这样过，重新登录chatgpt拿token 就好了
