### ISSUE TITLE
加了白名单的人发消息自动回复不了

### ISSUE THREAD

**Issue by Jackyobserver** [wangrongding/wechat-bot#130]
onScan: https://api.qrserver.com/v1/create-qr-code/?data=https%3A%2F%2Flogin.weixin.qq.com%2Fl%2FwbdNMTMLOw%3D%3D Waiting 2
19:00:04 INFO onScan: 3(undefined) Scanned
Contact<Jacky> has logged in
Current time:Sun Feb 26 2023 19:00:20 GMT+0800 (中国标准时间)
Automatic robot chat mode has been activated
{"_events":{},"_eventsCount":0,"id":"3852087032901574235","payload":{"id":"3852087032901574235","talkerId":"@886b78074ce6fcb0daf249a548b987705760ae26296d8e1d73a8ae6c0d31a261","text":"你好","timestamp":1677409224,"type":7,"listenerId":"@872cf824963dbb5f7edcad6f4363acc632f4bc797e8799f4663e674d1dd5cff7"}}

**Comment by slongZ** [comment]
我也是

**Comment by slongZ** [comment]
可以了，sendMessage.js文件下，30行
if (!content.startsWith('? ') && !content.startsWith('？ ') && !content.startsWith('> ')) return 
注释掉就可以了

**Comment by slongZ** [comment]
可能会有其他问题，那里的代码可以看着改改

**Comment by wangbo122** [comment]
msg.room()判断不出来是群消息

**Comment by hushlonelyhug** [comment]
> 可以了，sendMessage.js文件下，30行 if (!content.startsWith('? ') && !content.startsWith('？ ') && !content.startsWith('> ')) return 注释掉就可以了

debian11，注释，私聊群聊也没回复。

**Comment by slongZ** [comment]
> 

不是注释就行，注释只是处理其中一个问题，其他问题我没写，自己看看变量和判断都是干嘛用的，看看执行到哪出问题改下就行，不难的

**Comment by slongZ** [comment]
> > 可以了，sendMessage.js文件下，30行 if (!content.startsWith('? ') && !content.startsWith('？ ') && !content.startsWith('> ')) return 注释掉就可以了
> 
> debian11，注释，私聊群聊也没回复。


不是注释就行，注释只是处理其中一个问题，其他问题我没写，自己看看变量和判断都是干嘛用的，看看执行到哪出问题改下就行，不难的

**Comment by EvelynLuo** [comment]
求助 还是没有任何自动回复 console.log('🚀🚀🚀 / reply', reply)这句根本没有运行

**Comment by 331886820** [comment]
扫码后登陆 连个鬼都没有

**Comment by SakuyaKnowledge** [comment]
我有同样的问题，有没有能够详细解答的呢，而且我看我的openAi API usage里没有被调用的记录，是没有登上openAI吗

**Comment by fanfan2289** [comment]
> 我有同样的问题，有没有能够详细解答的呢，而且我看我的openAi API usage里没有被调用的记录，是没有登上openAI吗

解决了吗

**Comment by GadflyR** [comment]
我试的是消息要达到一定长度才会有回复

**Comment by TonyDiao2004** [comment]
> 求助 还是没有任何自动回复 console.log('🚀🚀🚀 / reply', reply)这句根本没有运行

我也是 后来解决了吗？

**Comment by wangrongding** [comment]
已修复，更新最新代码即可
