### ISSUE TITLE
接口调不同，是因为被墙了嘛？

### ISSUE THREAD

**Issue by MillionWang** [wangrongding/wechat-bot#134]
Error: connect ETIMEDOUT 199.16.156.7:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  errno: -60,
  code: 'ETIMEDOUT',
  syscall: 'connect',

**Comment by zhoumeng111** [comment]
一样的问题，科学上网也不行

**Comment by sseventeen** [comment]
我也碰见相同的问题了，解决了吗？

**Comment by wangrongding** [comment]
参考 #54 和最新README
