### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by Michelangelo-li** [wangrongding/wechat-bot#137]
10:34:07 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation timeout of 60000 ms exceeded
10:34:07 ERR PuppetWeChat initBridge() exception: Navigation timeout of 60000 ms exceeded
10:34:07 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.
是因为什么！

**Comment by QiuYeHong90** [comment]
我也是这个问题

**Comment by sharq34** [comment]
我也是这个问题，怎么解决

**Comment by totoleon** [comment]
+1

**Comment by ParadiseH** [comment]
+1

**Comment by waseemcn** [comment]
+1

**Comment by xiaotisos** [comment]
+1

**Comment by waseemcn** [comment]
解决办法：src/wechaty/index.js 
注释：
  puppet: 'wechaty-puppet-wechat',
  puppetOptions: {
    uos: true,
    ...CHROME_BIN
  },

**Comment by linbaochuan** [comment]
执行以下命令：
`npm i wechaty-puppet-wechat4u@1.13.12`

并且结合楼上的方法，
打开src/wechaty/index.js 将56行的注释取消掉，改成注释57行：

`export const bot = WechatyBuilder.build({
  name: 'WechatEveryDay',
   puppet: 'wechaty-puppet-wechat4u', // 如果有token，记得更换对应的puppet
  //puppet: 'wechaty-puppet-wechat', // 如果 wechaty-puppet-wechat 存在问题，也可以尝试使用上面的 wechaty-puppet-wechat4u ，记得安装 wechaty-puppet-wechat4u
  puppetOptions: {
    uos: true,
    ...CHROME_BIN
  },
})`
