### ISSUE TITLE
定时收到广告

### ISSUE THREAD

**Issue by hsk1995** [wangrongding/wechat-bot#138]
运行起来后，在日志里面会定时收到广告
![image](https://user-images.githubusercontent.com/40809868/224649464-33b35e71-9c6a-403d-bd82-a6397aab630d.png)
各位有同样情况的吗，是不是被劫持了消息

**Comment by hsk1995** [comment]
另外再问下   有没有知道如何清除登录状态的方式，每次启动的时候都会读取上次登录的账号  如果想要更换账号改怎么操作

**Comment by wangrongding** [comment]
这是你微信里的消息
