### ISSUE TITLE
之前成功了，现在使用报错不出现二维码，提示uncaughtException AssertionError [ERR_ASSERTION]: 1102 == 0

### ISSUE THREAD

**Issue by sseventeen** [wangrongding/wechat-bot#141]
> wechat-bot@1.0.0 dev
> node ./index.js

Start to log in wechat...
uncaughtException AssertionError [ERR_ASSERTION]: 1102 == 0
    at Object.equal (D:\wechatbot\wechat-bot-main\wechat-bot-main\node_modules\wechat4u\lib\util\global.js:69:24)
    at D:\wechatbot\wechat-bot-main\wechat-bot-main\node_modules\wechat4u\lib\core.js:227:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1102 == 0\n' +
    '    at Object.equal (D:\\wechatbot\\wechat-bot-main\\wechat-bot-main\\node_modules\\wechat4u\\lib\\util\\global.js:69:24)\n' +
    '    at D:\\wechatbot\\wechat-bot-main\\wechat-bot-main\\node_modules\\wechat4u\\lib\\core.js:227:24\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}

**Comment by sseventeen** [comment]
有没有大神知道怎么解决？求助求助

**Comment by wangrongding** [comment]
删除项目目录下的临时文件 WechatEveryDay.memory-card.json 即可

**Comment by tmKnight01** [comment]
没有用 删除之后还是会自动生成

onScan: https://api.qrserver.com/v1/create-qr-code/?data=
Waiting 2
11:58:38 INFO onScan: 3(undefined) Scanned
bot error❌:  AssertionError [ERR_ASSERTION]: 1 == 0
    at Object.equal (/Users/xin/Desktop/wechatGPT/wechat-bot/node_modules/wechat4u/lib/util/global.js:69:24)
    at /Users/xin/Desktop/wechatGPT/wechat-bot/node_modules/wechat4u/lib/core.js:229:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
    '    at Object.equal (/Users/xin/Desktop/wechatGPT/wechat-bot/node_modules/wechat4u/lib/util/global.js:69:24)\n' +
    '    at /Users/xin/Desktop/wechatGPT/wechat-bot/node_modules/wechat4u/lib/core.js:229:24\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}

**Comment by wangrongding** [comment]
肯定会自动生成的，我的意思是出问题的原因是你这个文件有问题，删除重新启动服务即可

**Comment by wangrongding** [comment]
大家都等一波吧，应该是用的人很多，最近微信查的好严格，其它同类型的项目都存在这个问题
主要是底层的 wechaty 他们也不怎么维护了。。。
