### ISSUE TITLE
你好目前只能和登录者窗口聊吗？

### ISSUE THREAD

**Issue by yangbuyiya** [wangrongding/wechat-bot#15]
不能和当前登录者所在的群聊里面聊吗

**Comment by wangrongding** [comment]
可以啊，在逻辑判断哪里改成相应的群聊试试

**Comment by yangbuyiya** [comment]
我判断了直接全部 如果是 @xxx就ok

**Comment by yangbuyiya** [comment]
ok了 需要进行判断 room的话 则调用 room.say 即可发送群聊

**Comment by yangbuyiya** [comment]
最终群聊效果 
![1670571543510](https://user-images.githubusercontent.com/52228969/206650096-7b8f2ac7-fa47-4ac1-aefa-b6b92cfe65db.png)

**Comment by wangrongding** [comment]
是的😅我这边网络也很差，所以只开了一个人的，开群聊直接就没了

**Comment by yangbuyiya** [comment]
哈哈哈直接崩 请求超时不给玩了
