### ISSUE TITLE
不自动回复

### ISSUE THREAD

**Issue by pqshao** [wangrongding/wechat-bot#151]
> > 不会自动回复。。。。 ![image](https://user-images.githubusercontent.com/43009132/224923804-8937c20f-5b2a-425e-9d1c-68822f3936f9.png)
> 
> 我和你一样，有解决吗

我也是，你们解决了吗？

_Originally posted by @by0126 in https://github.com/wangrongding/wechat-bot/issues/54#issuecomment-1545526874_

**Comment by pqshao** [comment]
openai调用问题

**Comment by zoechenry** [comment]
> 

您解决了吗
