### ISSUE TITLE
跑不起来， 运行后出现以下错误是怎么回事？

### ISSUE THREAD

**Issue by Shan1012** [wangrongding/wechat-bot#158]
23:27:25 WARN WechatyPuppetMixin start() starting puppet ... timeout
23:27:25 WARN WechatyPuppetMixin start() puppet info: Puppet<PuppetWeChat>(WechatEveryDay)
Start to log in wechat...
23:28:10 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation timeout of 60000 ms exceeded
23:28:10 ERR PuppetWeChat initBridge() exception: Navigation timeout of 60000 ms exceeded
23:28:10 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.

**Comment by wangrongding** [comment]
删掉 node_module 和 lock 文件，重新安装依赖
我最近更新依赖了
