### ISSUE TITLE
扫码登陆提示报错

### ISSUE THREAD

**Issue by cnjsyyb** [wangrongding/wechat-bot#160]
13:38:36 INFO onScan: 3(undefined) Scanned
uncaughtException GError [TypeError]: Cannot read properties of undefined (reading 'status')
    at /Users/yuanbin/Documents/wechat/wechat-bot/node_modules/wechat4u/lib/core.js:172:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: "TypeError: Cannot read properties of undefined (reading 'status')\n" +
    '    at /Users/yuanbin/Documents/wechat/wechat-bot/node_modules/wechat4u/lib/core.js:172:30\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}

**Comment by supdizh** [comment]
+1 求解答.....

**Comment by wangrongding** [comment]
更新最新代码尝试呢

**Comment by LynnHg** [comment]
> 更新最新代码尝试呢

你好，我用最新代码也是这个错误

**Comment by LynnHg** [comment]
> > 更新最新代码尝试呢
> 
> 你好，我用最新代码也是这个错误

看来是账号问题，换号可登录
