### ISSUE TITLE
npm run test 可以成功链接，但是npm run start后没有跳出选项

### ISSUE THREAD

**Issue by JiWu1993** [wangrongding/wechat-bot#172]
C:\Users\harve\Documents\mychat5\wechat-bot>npm run test

> wechat-bot@1.0.0 test
> node ./src/wechaty/testMessage.js

? 请先选择服务类型 ChatGPT
type:  ChatGPT
🚀🚀🚀 / prompt hello
🚀🚀🚀 / Using model gpt-3.5-turbo
🚀🚀🚀 / reply Hello! How can I assist you today?

🌸🌸🌸 / reply:  Hello! How can I assist you today?

Via gpt-3.5-turbo

C:\Users\harve\Documents\mychat5\wechat-bot>npm run start

> wechat-bot@1.0.0 start
> node ./cli.js

C:\Users\harve\Documents\mychat5\wechat-bot>

**Comment by wangrongding** [comment]
忘了提交一行代码，尴尬，请重新拉取最新代码
