### ISSUE TITLE
机器人不能自动应答

### ISSUE THREAD

**Issue by RobertHoffman** [wangrongding/wechat-bot#195]
我能够成功登录，但是不管我向机器人说什么，机器人都不回应。
我已经正确配置了kimi的密钥，使用npm run test测试成功。我也更新了.env文件中对应的白名单配置如下：
> #白名单配置
#定义机器人的名称，这里是为了防止群聊消息太多，所以只有艾特机器人才会回复，
#这里不要把@去掉，在@后面加上你启动机器人账号的微信名称
BOT_NAME=@陈晨
#联系人白名单
ALIAS_WHITELIST=月*
#群聊白名单
ROOM_WHITELIST=金*,文*

然后我向机器人发送消息，得到的是如下情况，机器人不回复：
![微信截图_20240709115523](https://github.com/wangrongding/wechat-bot/assets/43536186/af732673-e9a7-4ce9-97cf-2ed069460a87)

请问我应该怎么做？感谢~

**Comment by RobertHoffman** [comment]
我看了config.js里的数据也是正确的，并且登录的微信号的名称确实是“陈晨”。

**Comment by Sqhh99** [comment]
兄弟你解決了嗎？我的也是這樣，

**Comment by RobertHoffman** [comment]
> 兄弟你解決了嗎？我的也是這樣，

我没有啊，等等作者看有没有好办法

**Comment by Sqhh99** [comment]
刚刚已经把问题解决掉了，那个代码文件里面限制了文本text的格式，你的文本要在前面带‘?’、‘？’、'>'
![image](https://github.com/wangrongding/wechat-bot/assets/127586242/9046559b-8935-4141-854f-e110bc0cffc6)

**Comment by Sqhh99** [comment]
把那行代码注释掉再试试，如果还不行就是白名单设置有问题，而且这个kimi的ai接口好像限制挺高的，我运行的时候老是动不动就崩掉

**Comment by RobertHoffman** [comment]
> 把那行代码注释掉再试试，如果还不行就是白名单设置有问题，而且这个kimi的ai接口好像限制挺高的，我运行的时候老是动不动就崩掉

好的，马上去试试，谢谢
