### ISSUE TITLE
微信被识别到外挂封号了

### ISSUE THREAD

**Issue by lizhentao6a** [wangrongding/wechat-bot#198]
![PixPin_2024-07-12_10-49-24](https://github.com/user-attachments/assets/2d64327e-c6b7-41b9-ac83-f93bb086f471)

**Comment by zorrose82** [comment]
同样……刚人脸识别解封……

**Comment by lizhentao6a** [comment]
> 同样……刚人脸识别解封……

微信是有点恶心人的，去年听说就有过一次大规模的封号，也是wechaty

**Comment by 64log2** [comment]
是不是发消息太频繁了?

**Comment by lizhentao6a** [comment]
> 是不是发消息太频繁了?

感觉还行，不过也确实可能是有点频繁了

**Comment by l0g2** [comment]
> 根据[《微信个人账号使用规范》](https://weixin.qq.com/cgi-bin/readtemplate?&t=page/agreement/personal_account&lang=zh_CN)规定，微信明确禁止使用各类外挂。但近期我们发现，有部分用户存在多次违规使用外挂软件，或在朋友圈发布外挂售卖信息的行为。对此，微信安全团队进行了专项清理，并将持续加大清理力度。
> 常见的微信外挂类型：微信机器人：微信群营销，实现定时群发，自动回复，自动聊天等控制功能。
> -- [针对在微信使用“外挂”行为的打击公告](https://github.com/cixingguangming55555/wechat-bot?tab=readme-ov-file#notice), 2024年03月26日.
