### ISSUE TITLE
抱歉，这个扫码报错怎么搞啊？

### ISSUE THREAD

**Issue by AndyNull** [wangrongding/wechat-bot#2]
03:22:42 INFO onScan: 3(undefined) Scanned
03:23:42 WARN PuppetWatchdogAgent start() reset() reason: {"data":{"code":201,"url":"https://login.weixin.qq.com/qrcode/AZpheIC7hg=="},"timeoutMilliseconds":60000}
node:events:491
      throw er; // Unhandled 'error' event
      ^

GError: WatchdogAgent reset: lastFood: "{"data":{"code":201,"url":"https://login.weixin.qq.com/qrcode/AZpheIC7hg=="},"timeoutMilliseconds":60000}"
    at Watchdog.reset (file:///home/wechat-bot/node_modules/wechaty-puppet/dist/esm/src/agents/watchdog-agent.js:45:39)
    at Watchdog.emit (node:events:513:28)
    at Timeout._onTimeout (file:///home/wechat-bot/node_modules/watchdog/dist/esm/src/watchdog.js:81:18)

**Comment by wangrongding** [comment]
检查下node版本是否符合 README 文件中要求的哦~

**Comment by 5wszxt** [comment]
> 
刚试了，新注册的微信号会提示这个，经常用的正常登录了，但是没有交互。

就到这里，后面没反应
Contact<clown> has logged in
Current time:Wed Dec 07 2022 04:07:04 GMT-0500 (Eastern Standard Time)
Automatic robot chat mode has been activated

**Comment by 5wszxt** [comment]
> 👍到这里了就正常了
> 
> 你把这个地方改成你自己的需求就行了，我是因为消息太多了，只给这个指定备注名的好友发送信息 ![image](https://user-images.githubusercontent.com/42437658/206137585-b06f1ec6-e1ba-4a34-b533-f0593ba7a77b.png)

ok，这个棒，就是免打扰，哈哈

**Comment by wangrongding** [comment]
> 这个session只有一个月效期吧？

应该是一天不到

**Comment by yn-ayw** [comment]
如何让他回复所有呢，我改成回复所有，结果机器人一直再跟自己说话

**Comment by wangrongding** [comment]
> 如何让他回复所有呢，我改成回复所有，结果机器人一直再跟自己说话

room.say(reply);
