### ISSUE TITLE
机器人回答问题发两次消息第二次消息不在微信中显示（回答一个问题不连贯，发两段消息第二段没发出来），怎么解决。

### ISSUE THREAD

**Issue by 12316joker** [wangrongding/wechat-bot#23]
![1670728987](https://user-images.githubusercontent.com/120159224/206884798-4855ab6c-961c-43fc-8ac7-2105904d0d28.jpg)
![1670728987(1)](https://user-images.githubusercontent.com/120159224/206884801-6e6be336-70e9-4522-8339-95df496911b5.jpg)

**Comment by 12316joker** [comment]
还有一个问题就是他好像会跟自己聊天但不会在群聊中发送出来
![image](https://user-images.githubusercontent.com/120159224/206885069-f7fc0ac6-dbb9-464a-826d-c71ae0e28dce.png)

**Comment by wangrongding** [comment]
还有这操作？你好，如何复现呢？

**Comment by 183673639** [comment]
我私聊的情况下也遇到这个问题了，会把自己的回复当成我发的内容然后一直自己循环下去，超过微信最大发送字数就会报错

**Comment by wangrongding** [comment]
哦哦，最新版的已经处理了这个问题，你重新试一下，如果没问题了可以回到这边关闭这个 issue

**Comment by 183673639** [comment]
发问题的人和接收回答的人如果是同一个人就会出现这种循环
