### ISSUE TITLE
有没有专门类似于调用微信方法的文档？

### ISSUE THREAD

**Issue by XuYingJie-cmd** [wangrongding/wechat-bot#242]
有没有专门类似于调用微信方法的文档？

**Comment by wangrongding** [comment]
可以查看wechaty的官方文档

**Comment by XuYingJie-cmd** [comment]
> 可以查看微信的官方文档

现在还有两个小问题啊 1是卡片好像没法直接用？ 2是filebox.fromurl中的文件大小貌似被限制在25M以上就会发送失败请问怎么处理？
