### ISSUE TITLE
npm 7.21.1  node16.9.1 Ubuntu 22.04.1 LTS can not run,  because The requested module 'wechaty' is a CommonJS module, which may not support all module.exports as named exports. Could every body tell me why?

### ISSUE THREAD

**Issue by slongli** [wangrongding/wechat-bot#27]
import { WechatyBuilder, ScanStatus, log } from "wechaty";
         ^^^^^^^^^^^^^^
SyntaxError: Named export 'WechatyBuilder' not found. The requested module 'wechaty' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'wechaty';
const { WechatyBuilder, ScanStatus, log } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:179:5)
    at async Loader.import (node:internal/modules/esm/loader:178:24)
    at async Object.loadESM (node:internal/process/esm_loader:68:5)
    at async handleMainPromise (node:internal/modules/run_main:63:12)

**Comment by wangrongding** [comment]
Try using the node LTS version

**Comment by ronaldox** [comment]
> Try using the node LTS version

我和他是一样的错，更换了nodejs最新LTS版本也不行

**Comment by slongli** [comment]
我应该是这样解决了，你试试，sudo npm install qrcode-terminal --save sudo npm install wechaty  sudo npm install wechaty-puppet-wechat --save



------------------&nbsp;Original message&nbsp;------------------
From: "ronaldox"; 
Sendtime: Tuesday, Dec 13, 2022 2:28 AM
To: "wangrongding/wechat-bot"; 
Cc: " ***@***.***>; "Author"; 
Subject: Re: [wangrongding/wechat-bot] npm 7.21.1  node16.9.1 Ubuntu 22.04.1 LTS can not run,  because The requested module &#39;wechaty&#39; is a CommonJS module, which may not support all module.exports as named exports. Could every body tell me why? (Issue #27)





  
Try using the node LTS version
  
我和他是一样的错，更换了nodejs最新LTS版本也不行

**Comment by wangrongding** [comment]
或者先参考这个方案。
https://github.com/wangrongding/wechat-bot/issues/54#issuecomment-1347743629
