### ISSUE TITLE
npm run dev 跑起来，二维码出不来是什么问题？

### ISSUE THREAD

**Issue by cjumna** [wangrongding/wechat-bot#30]
二维码出不来是什么问题？
root@22-7-24-0556:/volume1/docker/wechatbot# npm run dev

> wechat-boot@1.0.0 dev
> node ./index.js

20:00:21 WARN WechatyPuppetMixin start() starting puppet ... timeout
20:00:21 WARN WechatyPuppetMixin start() puppet info: Puppet<PuppetWeChat>(WechatEveryDay)
Start to log in wechat...
20:01:19 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation timeout of 60000 ms exceeded
20:01:19 ERR PuppetWeChat initBridge() exception: Navigation timeout of 60000 ms exceeded
20:01:19 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.

**Comment by wangrongding** [comment]
网络超时了你

**Comment by ycs0220** [comment]
解决了吗？我也遇到了这个问题

**Comment by loyal-ding** [comment]
> 换了另外一个程序是什么意思？

**Comment by PoleWick** [comment]
我也这样，但是用别的项目没问题
