### ISSUE TITLE
最新的貌似403forbidden了

### ISSUE THREAD

**Issue by f0ng** [wangrongding/wechat-bot#34]
2022.12.12
主要问题出在了认证貌似新增了，修改如下：
```javascript
// 定义ChatGPT的配置
const config = {
  markdown: true, // 返回的内容是否需要markdown格式
  AutoReply: true, // 是否自动回复
  clearanceToken: dotenv.config().parsed.CHATGPT_CLEARANCE,// ChatGPT的clearance，从cookie取值
  sessionToken: dotenv.config().parsed.CHATGPT_SESSION_TOKEN, // ChatGPT的sessionToken
  userAgent: dotenv.config().parsed.CHATGPT_USER_AGENT, // User-Agent
  accessToken:dotenv.config().parsed.CHATGPT_ACCESS_TOKEN// 在用户授权情况下，访问https://chat.openai.com/api/auth/session，获取accesstoken
}
```

.env如下
```json
CHATGPT_SESSION_TOKEN=''
CHATGPT_CLEARANCE=''
CHATGPT_USER_AGENT=''
CHATGPT_ACCESS_TOKEN=''
```

<img width="598" alt="image" src="https://user-images.githubusercontent.com/48286013/206950992-ebc865fd-ae70-49e7-99a6-4f9225164031.png">

**Comment by wangrongding** [comment]
愿意提一个 PR 嘛~ 非常感谢

**Comment by f0ng** [comment]
已提(*^▽^*)

**Comment by lisiyizu** [comment]
好像还是报403 ，chatgpt已经升级到 v2.1.1

(node:14328) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
ChatGPTError: ChatGPTAPI error 403
    at fetchSSE (file:///Users/xxx/Documents/work/chatGPT/wechat-bot/node_modules/chatgpt/build/index.js:80:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  statusCode: 403,
  statusText: 'Forbidden',
  response: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 403,
      timingInfo: [Object],
      cacheState: '',
      statusText: 'Forbidden',
      headersList: [HeadersList],
      urlList: [Array],
      body: [Object]
    },
    [Symbol(headers)]: HeadersList {
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  }
}

**Comment by f0ng** [comment]
问题出在`clearanceToken`与`sessionToken`上，需要重新刷新或者重新登录获取

**Comment by ZoeYingY** [comment]
> 好像还是报403 ，chatgpt已经升级到 v2.1.1
> 
> ```
> (node:14328) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
> (Use `node --trace-warnings ...` to show where the warning was created)
> ChatGPTError: ChatGPTAPI error 403
>     at fetchSSE (file:///Users/xxx/Documents/work/chatGPT/wechat-bot/node_modules/chatgpt/build/index.js:80:19)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
>   statusCode: 403,
>   statusText: 'Forbidden',
>   response: Response {
>     [Symbol(realm)]: null,
>     [Symbol(state)]: {
>       aborted: false,
>       rangeRequested: false,
>       timingAllowPassed: true,
>       requestIncludesCredentials: true,
>       type: 'default',
>       status: 403,
>       timingInfo: [Object],
>       cacheState: '',
>       statusText: 'Forbidden',
>       headersList: [HeadersList],
>       urlList: [Array],
>       body: [Object]
>     },
>     [Symbol(headers)]: HeadersList {
>       [Symbol(headers map)]: [Map],
>       [Symbol(headers map sorted)]: null
>     }
>   }
> }
> ```

请问您解决了吗？重新登陆后仍旧报错403

**Comment by wangrongding** [comment]
😅 感觉大家还是要看下 README 文档，因为 chatgpt添加了一些限制，所以在配置上，我们新增了几个环境变量，您需要去拿到对应的参数后补充完整才可以用哈~

**Comment by lisiyizu** [comment]
> 😅 感觉大家还是要看下 README 文档，因为 chatgpt添加了一些限制，所以在配置上，我们新增了几个环境变量，您需要去拿到对应的参数后补充完整才可以用哈~

加了四个参数，刷新了重新获取了 clearanceToken与sessionToken，依然报 403

**Comment by wangrongding** [comment]
🧐难道又限制又升级了？ 晚上我看下，大家有空可以自行排查下，需要改的地方可以提一个 PR 我直接合并。
相应的库是：[问题详情](https://github.com/transitive-bullshit/chatgpt-api#update-december-11-2022)

**Comment by f0ng** [comment]
有时参数不对应也会403，得多试几次才成功，或者可以直接把参数填入`const config`内，如
```bash
  clearanceToken: 'xxxxxxxxxxxx',
  sessionToken: 'xxxxxxxxxxxxxx', // ChatGPT的sessionToken
  userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) xxxxxxxxxxxxxxx',//获取sessionToken时的UA头，通过开发者工具F12在network处获取
  accessToken:'eyJhbGciOiJSxxxxxxxxxxxxxxxxxxxxx'
```

以下为不正确的参数报错，是403，后续修改参数，成功

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/48286013/206972344-85b05529-ab37-4a7b-8970-2ad2bfcac011.png">

**Comment by lisiyizu** [comment]
<img width="1044" alt="image" src="https://user-images.githubusercontent.com/12014252/206975800-bc0a9185-0a88-417e-81ff-eb76d12db15d.png">

奇怪了，我获取最新的 clearanceToken与sessionToken ，反复测试了好多次一直报错。

**Comment by moxinnai** [comment]
<img width="427" alt="image" src="https://user-images.githubusercontent.com/35122353/206980118-7193803d-72c0-46d6-92fe-eabe8433e211.png">
<img width="460" alt="image" src="https://user-images.githubusercontent.com/35122353/206980287-0e173a5a-563c-49b1-a861-c8f7a03ecf07.png">
debug了，还是403

**Comment by emmmnaadada** [comment]
仍然报错

**Comment by jia1076999758** [comment]
@emmmnaadada 一样403

**Comment by baoheng233** [comment]
凭证直接赋值给到const config方法也是403
![image](https://user-images.githubusercontent.com/77369542/207005680-26e7f818-27c5-4b3f-b5df-80907d3a3c66.png)

**Comment by wangrongding** [comment]
修复了同志们，具体看 readme

**Comment by ycs0220** [comment]
> 有时参数不对应也会403，得多试几次才成功，或者可以直接把参数填入`const config`内，如
> 
> ```shell
>   clearanceToken: 'xxxxxxxxxxxx',
>   sessionToken: 'xxxxxxxxxxxxxx', // ChatGPT的sessionToken
>   userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) xxxxxxxxxxxxxxx',//获取sessionToken时的UA头，通过开发者工具F12在network处获取
>   accessToken:'eyJhbGciOiJSxxxxxxxxxxxxxxxxxxxxx'
> ```
> 
> 以下为不正确的参数报错，是403，后续修改参数，成功
> 
> <img alt="image" width="1058" src="https://user-images.githubusercontent.com/48286013/206972344-85b05529-ab37-4a7b-8970-2ad2bfcac011.png">

你好，我反复修改很多次都没用，请问有什么思路吗？

**Comment by ycs0220** [comment]
> 凭证直接赋值给到const config方法也是403 ![image](https://user-images.githubusercontent.com/77369542/207005680-26e7f818-27c5-4b3f-b5df-80907d3a3c66.png)

请问解决了嘛？用chatgpt我也遇到了一样的报错。

**Comment by ycs0220** [comment]
> <img alt="image" width="1044" src="https://user-images.githubusercontent.com/12014252/206975800-bc0a9185-0a88-417e-81ff-eb76d12db15d.png">
> 
> 奇怪了，我获取最新的 clearanceToken与sessionToken ，反复测试了好多次一直报错。

请问解决了嘛？

**Comment by ycs0220** [comment]
> <img alt="image" width="1044" src="https://user-images.githubusercontent.com/12014252/206975800-bc0a9185-0a88-417e-81ff-eb76d12db15d.png">
> 
> 奇怪了，我获取最新的 clearanceToken与sessionToken ，反复测试了好多次一直报错。

用chatgpt我也遇到了一样的报错，请问现在解决了吗？
