### ISSUE TITLE
请问方便给此 repository 添加合适的协议吗？

### ISSUE THREAD

**Issue by AlanGolphi** [wangrongding/wechat-bot#36]
我想借鉴该仓库部分代码做些小玩意，但是该仓库没有对应的协议，我不确定我参考(copy)代码的行为是否合适，麻烦为该项目添加合适的协议，谢谢 @wangrongding

**Comment by wangrongding** [comment]
好的，没问题，是否愿意简单的提一个 PR？ 放一个 MIT 的协议

**Comment by wangrongding** [comment]
ok
