### ISSUE TITLE
启动时报错，但是在npm install之后也无法安装chrome

### ISSUE THREAD

**Issue by JacksonTom** [wangrongding/wechat-bot#40]
启动时报错，但是在npm install之后也无法安装chrome
![image](https://user-images.githubusercontent.com/38249260/207013437-debb25c1-02fc-4c64-bf5b-32265c34d65a.png)

**Comment by wangrongding** [comment]
可能依赖安装不成功，切到 taobao 镜像源，删除 node_modules ,再重新安装试试；
推荐使用我的 [prm-cli](https://github.com/wangrongding/prm-cli) 工具切换。

**Comment by zq970825** [comment]
我也是这样，反复安装依赖也都不行，node版本也是18.12.1

**Comment by wangrongding** [comment]
先参考这个方案。
https://github.com/wangrongding/wechat-bot/issues/54#issuecomment-1347743629

**Comment by OnePieceJoker** [comment]
我的一个暂时不优雅的解决方案是：
在你报错的那个顶层文件里，手动配置下Chromium安装路径。

按照你的问题来看的话，就是在Launcher.js报错的那个方法里找到executablePath，手动设置下Chromium路径。

Chromium路径在你的node_modules/puppeteer/.local-chromium/xxx下
