### ISSUE TITLE
请问为什么我这个好像不是chatgpt

### ISSUE THREAD

**Issue by PrinsYin** [wangrongding/wechat-bot#43]
![1670842637894](https://user-images.githubusercontent.com/32424487/207028347-9f3ea4a9-faee-4e28-acba-78f8d0797d41.jpg)

**Comment by woshiawu666** [comment]
我的也是，像个智障

**Comment by Linkada** [comment]
感觉瞬间从青少年退化成了一个智障

**Comment by wangrongding** [comment]
<img width="481" alt="image" src="https://user-images.githubusercontent.com/42437658/207098474-ae9cde2c-72b2-4f72-9fab-8911b2b1cff2.png">
已经修改了长度限制，并且去除了 markdown标记， 你也可以自行修改配置哈。 语言模型之类的，都可以根据文档自行修改

**Comment by wangrongding** [comment]
ok，我晚点去弄下，感谢您的提醒
