### ISSUE TITLE
无法找到puppeteer的执行路径

### ISSUE THREAD

**Issue by MFamilys** [wangrongding/wechat-bot#47]
安装依赖成功，运行npm run dev 时报错：'Error: An `executablePath` or `channel` must be specified for `puppeteer-core`\n'

**Comment by RickWashon** [comment]
> 

我也出现了这个问题，但是我之前用的好好的，然后退出登录后，就出现这个问题了。重新安装也没用，用博主说的这个方法也没用。下载了新的wechat-bot也没用

**Comment by zq970825** [comment]
我也是这样，反复安装依赖也都不行，node版本也是18.12.1

**Comment by Reckless1998** [comment]
删了 node_modules 后，切换到 taobao 源还是报 ERR PuppetWeChatBridge start() exception: Error: An `executablePath` or `channel` must be specified for `puppeteer-core` 找不到路径

**Comment by Axpoii** [comment]
同也是这个问题，node版本 v19.2.0

**Comment by wangrongding** [comment]
你们都是什么操作系统？方便说一下吗？看到不少小伙伴都出现了这个问题

**Comment by zq970825** [comment]
windows11

**Comment by OnePieceJoker** [comment]
macos 11.6.2
node version v18.11.0

**Comment by wangrongding** [comment]
先参考这个方案

https://github.com/wangrongding/wechat-bot/issues/54#issuecomment-1347743629

**Comment by Reckless1998** [comment]
> 你们都是什么操作系统？方便说一下吗？看到不少小伙伴都出现了这个问题

macos
