### ISSUE TITLE
他的话老是说到一半就不说了，不知道是什么原因导致的？

### ISSUE THREAD

**Issue by slongli** [wangrongding/wechat-bot#48]
![image](https://user-images.githubusercontent.com/41559429/207076594-8e626316-d246-4b8d-878e-fd600bc5d3ca.png)

**Comment by wangrongding** [comment]
<img width="481" alt="image" src="https://user-images.githubusercontent.com/42437658/207098474-ae9cde2c-72b2-4f72-9fab-8911b2b1cff2.png">
已经修改了，长度限制，你也可以自行修改哈
