### ISSUE TITLE
如何限定某一个群，并在群里回复？

### ISSUE THREAD

**Issue by wa1nu7** [wangrongding/wechat-bot#5]
如何限定某一个群，并在群里回复？

**Comment by wangrongding** [comment]
你可以在 onMessage 回调里把 room 打印出来，有 id 和名称的，对应判断就行

**Comment by Recogn1z** [comment]
> 你可以在 onMessage 回调里把 room 打印出来，有 id 和名称的，对应判断就行

请问可以详细讲一讲吗 试了很多次都不太行 对java不是很懂 qwq

**Comment by wangrongding** [comment]
🥲这是 js，不是 java，把源码里的那几个变量打印出来看看就可以了，然后对应的做限制，如果这个都不懂的话，建议先看下前端基础哈~

**Comment by dossweet** [comment]
@wangrongding 作者您好，我按照您的说话监听了指定的群消息，但是为什么群中发送的消息没有在群聊中回复，而是私发给了这个在群里发消息的人呢？是我写法不对吗？
![image](https://user-images.githubusercontent.com/38655923/206720738-064aa7db-cfc2-40d7-bb57-0fb4b90e273d.png)

**Comment by dossweet** [comment]
解决了，群消息要用room.say(reply);
