### ISSUE TITLE
 prm: command not found

### ISSUE THREAD

**Issue by ahuaiph** [wangrongding/wechat-bot#51]
[root@iZ2zedZ WeChat_Bot]# npm i prm-cli -g
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

changed 133 packages, and audited 389 packages in 7s

26 packages are looking for funding
  run `npm fund` for details

30 vulnerabilities (2 low, 11 moderate, 12 high, 5 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
[root@iZ2zedZ  WeChat_Bot]# 
[root@iZ2zedZ  WeChat_Bot]# 
[root@iZ2zedZ  WeChat_Bot]# 
[root@iZ2zedZ  WeChat_Bot]# prm test
bash: prm: command not found
[root@iZ2zedZ  WeChat_Bot]# 
[root@iZ2zedZ  WeChat_Bot]# 
[root@iZ2zedZ  WeChat_Bot]# 
[root@iZ2zedZ  WeChat_Bot]# prm-cli
bash: prm-cli: command not found

**Comment by OnePieceJoker** [comment]
命令是prm

**Comment by ahuaiph** [comment]
不是这个问题，prm命令直接敲也是报找不到该命令；
看看npm i prm-cli -g的安装命令，报了几个问题：
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade to version 7 or higher. Older versions may use Math.random() in certain circumstances, which is known to be problematic. See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

这几个包显示不再支持

**Comment by ahuaiph** [comment]
[root@iZ2zedZ prm-cli]# npm i

up to date, audited 388 packages in 12s

26 packages are looking for funding
  run `npm fund` for details

30 vulnerabilities (2 low, 11 moderate, 12 high, 5 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.
[root@iZ2zedZ prm-cli]# npm fund
prm-cli@0.0.30
├── https://github.com/chalk/chalk?sponsor=1
│   └── chalk@5.2.0
├── https://github.com/sponsors/sindresorhus
│   └── ansi-escapes@6.0.0, type-fest@3.3.0, cli-cursor@4.0.0, restore-cursor@4.0.0, onetime@5.1.2, figures@5.0.0, escape-string-regexp@5.0.0, is-unicode-supported@1.3.0, ora@6.1.2, cli-spinners@2.7.0, is-interactive@2.0.0, log-symbols@5.1.0, defaults@1.0.4, string-width@5.1.2
├─┬ https://github.com/chalk/strip-ansi?sponsor=1
│ │ └── strip-ansi@7.0.1
│ └── https://github.com/chalk/ansi-regex?sponsor=1
│     └── ansi-regex@6.0.1
├─┬ https://github.com/chalk/wrap-ansi?sponsor=1
│ │ └── wrap-ansi@8.0.1
│ └── https://github.com/chalk/ansi-styles?sponsor=1
│     └── ansi-styles@6.2.1
└── https://github.com/sponsors/epoberezkin
    └── ajv@6.12.6

[root@iZ2zedZ prm-cli]# 
[root@iZ2zedZ prm-cli]# prm
bash: prm: command not found

**Comment by wangrongding** [comment]
暂时先参考这个解决吧。

https://github.com/wangrongding/wechat-bot/issues/54?notification_referrer_id=NT_kwDOAoeMGrM1MDcyMzY5MTU5OjQyNDM3NjU4#issuecomment-1347880291

**Comment by ahuaiph** [comment]
![image](https://user-images.githubusercontent.com/49918030/207265916-ff5a3942-6107-48a2-9d20-082dd7886d19.png)

也是一样，没法解决
