### ISSUE TITLE
ChatAPI error

### ISSUE THREAD

**Issue by shouxieai** [wangrongding/wechat-bot#52]
ChatGPTError: ChatGPTAPI error 403
    at fetchSSE (file:///D:/download/wechat-bot-main/wechat-bot-main/node_modules/chatgpt/build/index.js:80:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 403,
  statusText: 'Forbidden',
  response: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 403,
      timingInfo: [Object],
      cacheState: '',
      statusText: 'Forbidden',
      headersList: [HeadersList],
      urlList: [Array],
      body: [Object]
    },
    [Symbol(headers)]: HeadersList {
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  }
}

**Comment by wangrongding** [comment]
更新下代码，最新的不会
