### ISSUE TITLE
429 too many requests

### ISSUE THREAD

**Issue by LeiSanity** [wangrongding/wechat-bot#55]
Have you ever encountered this situation? how did you handle it?
` response: {
    status: 429,
    statusText: 'Too Many Requests',
    headers: {
      date: 'Tue, 13 Dec 2022 07:13:47 GMT',
      'content-type': 'application/json; charset=utf-8',
      'content-length': '206',
      connection: 'keep-alive',
      vary: 'Origin',
      'x-request-id': '56ee37385e9dcd3906f9d8e61a75c58e',
      'strict-transport-security': 'max-age=15724800; includeSubDomains'
    },`

**Comment by waahah** [comment]
Too hot, the official website can not bear, directly landed on the official website can not go in, and so on for another time
