### ISSUE TITLE
node镜像中运行 npm run dev 报错

### ISSUE THREAD

**Issue by imfifc** [wangrongding/wechat-bot#56]
我使用的node容器安装的，docker pull node 
07:18:36 ERR PuppetWeChatBridge start() exception: Error: An `executablePath` or `channel` must be specified for `puppeteer-core`
![image](https://user-images.githubusercontent.com/53161431/207251571-2384a65e-8a92-43b5-9211-9cf9aa56e2b5.png)

**Comment by LeiSanity** [comment]
#54 check this issue, may help u.

**Comment by wangrongding** [comment]
暂时先参考这个解决吧。

https://github.com/wangrongding/wechat-bot/issues/54?notification_referrer_id=NT_kwDOAoeMGrM1MDcyMzY5MTU5OjQyNDM3NjU4#issuecomment-1347880291
