### ISSUE TITLE
谨慎使用 ！！！我调试好，以同事微信被封禁结束！

### ISSUE THREAD

**Issue by ImmortalBro** [wangrongding/wechat-bot#58]
![image](https://user-images.githubusercontent.com/17041619/207274791-83f7e345-34bd-4fe2-8176-e4fb542e57de.png)
谨慎使用 ！！！我调试好，以同事微信被封禁结束！

**Comment by xinyuanlee** [comment]
被微信强退警告了

**Comment by jiang263** [comment]
me too

**Comment by jia1076999758** [comment]
me too

**Comment by wangrongding** [comment]
最好都用小号玩玩先吧，这几天应该是严查，昨天不少小伙伴都收到警告了。

**Comment by code4u2** [comment]
me too
