### ISSUE TITLE
运行后打印超时

### ISSUE THREAD

**Issue by aa66952167** [wangrongding/wechat-bot#67]
16:05:10 WARN WechatyPuppetMixin start() starting puppet ... timeout
16:05:10 WARN WechatyPuppetMixin start() puppet info: Puppet<PuppetWeChat>(WechatEveryDay)
Start to log in wechat...
16:05:56 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation timeout of 60000 ms exceeded
16:05:56 ERR PuppetWeChat initBridge() exception: Navigation timeout of 60000 ms exceeded
16:05:56 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.

**Comment by ycs0220** [comment]
> 16:05:10 WARN WechatyPuppetMixin start() starting puppet ... timeout 16:05:10 WARN WechatyPuppetMixin start() puppet info: Puppet(WechatEveryDay) Start to log in wechat... 16:05:56 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation timeout of 60000 ms exceeded 16:05:56 ERR PuppetWeChat initBridge() exception: Navigation timeout of 60000 ms exceeded 16:05:56 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.

请问解决了嘛？我也遇到了类似的报错，如下：
![image](https://user-images.githubusercontent.com/34889631/212247318-780ae349-f3b4-4450-b6b9-97ea3ab847bd.png)
