### ISSUE TITLE
PuppetWeChatBridge start() exception: TimeoutError

### ISSUE THREAD

**Issue by udbyygyt** [wangrongding/wechat-bot#73]
[root@VM-0-15-centos wechat-bot]# npm run dev

> wechat-boot@1.0.0 dev
> node ./index.js

14:25:13 WARN WechatyPuppetMixin start() starting puppet ... timeout
14:25:13 WARN WechatyPuppetMixin start() puppet info: Puppet<PuppetWeChat>(WechatEveryDay)
Start to log in wechat...
14:25:59 ERR PuppetWeChatBridge start() exception: TimeoutError: Navigation timeout of 60000 ms exceeded
14:25:59 ERR PuppetWeChat initBridge() exception: Navigation timeout of 60000 ms exceeded
14:25:59 WARN PuppetWeChatBridge stop() page.close() exception: Error: Protocol error: Connection closed. Most likely the page has been closed.

启动调起微信超时了，这个怎么弄？
新加坡的linux服务器

**Comment by gladpieland** [comment]
我也遇到类似问题，是通过下载指定的puppeteer(13.5.1)和chromium(970485), 解决这个问题

**Comment by WestLee1207** [comment]
> 我也遇到类似问题，是通过下载指定的puppeteer(13.5.1)和chromium(970485), 解决这个问题

我也遇到了这个问题，要修改什么文件解决？
