### ISSUE TITLE
感觉和openai官网的chatgpt用起来差别很大呀，不像是chatgpt回复的，这是为什么

### ISSUE THREAD

**Issue by YuzheZhang-1999** [wangrongding/wechat-bot#83]

**Comment by ycs0220** [comment]
请问有链接chatgpt的教程吗？

**Comment by wangrongding** [comment]
里面有两种哈，你可以自己选一种，目前用的是官方的 openai 提供的，当然也有第三方封装好了的 ChatGPT 的库

<img width="436" alt="image" src="https://user-images.githubusercontent.com/42437658/212524554-79a14fb3-9b87-4bc3-b8a7-4db2291cb6f8.png">

**Comment by ycs0220** [comment]
> 里面有两种哈，你可以自己选一种，目前用的是官方的 openai 提供的，当然也有第三方封装好了的 ChatGPT 的库
> 
> <img alt="image" width="436" src="https://user-images.githubusercontent.com/42437658/212524554-79a14fb3-9b87-4bc3-b8a7-4db2291cb6f8.png">

请问目前是可用的吗？

**Comment by wangrongding** [comment]
都可用的，Openai 的可以根据官网给出的文档调整参数值，第三方的也很方便，可以看 [这个仓库](https://github.com/transitive-bullshit/chatgpt-api) 的 README

**Comment by ycs0220** [comment]
> 都可用的，Openai 的可以根据官网给出的文档调整参数值，第三方的也很方便，可以看 [这个仓库](https://github.com/transitive-bullshit/chatgpt-api) 的 README

好的，谢谢，我去试试看。

**Comment by ycs0220** [comment]
> 值

请问CHATGPT_USER_AGENT值如何获取

**Comment by ycs0220** [comment]
> 都可用的，Openai 的可以根据官网给出的文档调整参数值，第三方的也很方便，可以看 [这个仓库](https://github.com/transitive-bullshit/chatgpt-api) 的 README

你好，我改成chatgpt之后，登入上微信。在回复信息的时候，终端上出现如下的打印，请问有思路吗？
<img width="934" alt="image" src="https://user-images.githubusercontent.com/34889631/212527858-34512974-585b-4545-80cd-2c48163d35bb.png">

**Comment by wangrongding** [comment]
这个具体要跟着那个仓库的说明走了，因为是第三方的，所以第一是不稳定，第二是官方改了它得对应着改，没改就出问题

**Comment by b0bcx** [comment]
> > 都可用的，Openai 的可以根据官网给出的文档调整参数值，第三方的也很方便，可以看 [这个仓库](https://github.com/transitive-bullshit/chatgpt-api) 的 README
> 
> 你好，我改成chatgpt之后，登入上微信。在回复信息的时候，终端上出现如下的打印，请问有思路吗？ <img alt="image" width="934" src="https://user-images.githubusercontent.com/34889631/212527858-34512974-585b-4545-80cd-2c48163d35bb.png">

问一下怎么更换的 是改根目录下index.js里的地址吗
