### ISSUE TITLE
按照上面方法解决puppeteer-core问题，引出下面问题

### ISSUE THREAD

**Issue by yangyangpig** [wangrongding/wechat-bot#84]
mac M1系统
报错
![image](https://user-images.githubusercontent.com/15599854/213344347-bf6d3cbb-3824-41a2-b778-37a818701088.png)

**Comment by Edward-1989** [comment]
我也是Mac M1，出现了一样的问题

**Comment by yangyangpig** [comment]
> 我也是Mac M1，出现了一样的问题

你解决这个问题了吗？好像没人回答

**Comment by wangrongding** [comment]
#54
