### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by Wepre** [wangrongding/wechat-bot#85]
![image](https://user-images.githubusercontent.com/70182776/214771350-3e51302e-ce19-4cff-828d-f07141e1a2ff.png)
npm run dev 报错
上一步npm i已经好了，如图。
![image](https://user-images.githubusercontent.com/70182776/214771450-60555b00-f136-40c8-ac80-d4fe41918018.png)
求解答

**Comment by wangrongding** [comment]
#54
