### ISSUE TITLE
安装依赖的时候报错

### ISSUE THREAD

**Issue by Victor94-king** [wangrongding/wechat-bot#91]
![image](https://user-images.githubusercontent.com/103173758/216883168-5f3a1860-52a5-4e77-b964-e73c88aeb3d0.png)
有朋友遇到类似的问题么。。。 安装npm i 的时候报错。

@wangrongding 老铁帮忙看看？

**Comment by ryan0562** [comment]
换淘宝镜像、node18+

**Comment by Victor94-king** [comment]
![image](https://user-images.githubusercontent.com/103173758/216883399-7934417b-db0e-4317-b59d-5b0be55cfae3.png)
更新一下

**Comment by Victor94-king** [comment]
> 换淘宝镜像、node18+

![image](https://user-images.githubusercontent.com/103173758/216884243-2ead43f6-f2fd-456a-9abb-ba30a3f41b94.png)
这样是node18+吗
