### ISSUE TITLE
Docker 构建失败

### ISSUE THREAD

**Issue by GeorgeGalway** [wangrongding/wechat-bot#94]

**Comment by Wiki1991** [comment]
Dockerfile里试下把debian的源换国内
`RUN sed -i s/deb.debian.org/mirrors.aliyun.com/g /etc/apt/sources.list && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone`

**Comment by wangrongding** [comment]
谁这块提个 PR，我一会合并下

**Comment by saiwas** [comment]
@wangrongding , Could you please take a look on above PR?

**Comment by wangrongding** [comment]
> @wangrongding , Could you please take a look on above PR?

Okay, I've merged.
