### ISSUE TITLE
chatgpt-api.ts:247:29   statusCode: 404

### ISSUE THREAD

**Issue by zhaoyong123** [wangrongding/wechat-bot#97]
![image](https://user-images.githubusercontent.com/29479569/217408567-b063e9a7-6bfe-4116-957b-e9cba6fe6dfd.png)
昨天还运行好好的，今天就报这个错。重启过几次也一样

**Comment by jackyma001** [comment]
chatgpt-api默认使用的模型是var CHATGPT_MODEL = "text-chat-davinci-002-20221122"， 这个是不收费的。
改成var CHATGPT_MODEL = "text-davinci-003"; 就可以了，不过这个是要消耗你账户里预存的18美元的。
